const {
  Category,
  User,
  Ledger,
  Transaction,
  SupportPost,
} = require("../models");
const bcrypt = require("bcrypt");

//카테고리
const seedCategories = async () => {
  const categories = [
    { id: 1, name: "식비" },
    { id: 2, name: "취미" },
    { id: 3, name: "여가" },
    { id: 4, name: "병원" },
    { id: 5, name: "카페" },
    { id: 6, name: "교육" },
    { id: 7, name: "쇼핑" },
    { id: 8, name: "주거/통신" },
    { id: 9, name: "편의점" },
    { id: 10, name: "교통" },
    { id: 11, name: "이체" },
    { id: 12, name: "월급" },
    { id: 13, name: "용돈" },
    { id: 14, name: "기타 부수입" },
  ];

  for (const category of categories) {
    await Category.findOrCreate({
      where: { name: category.name },
    });
  }
  console.log("카테고리 시드 완료");
};

//user
const seedUsers = async () => {
  const users = [
    {
      id: 1,
      name: "user",
      email: "email@example.com",
      password: "1234",
      role: "user",
    },
    {
      id: 2,
      name: "admin",
      email: "admin@example.com",
      password: "1234",
      role: "admin",
    },
    {
      id: 3,
      name: "user2",
      email: "user2@example.com",
      password: "123456",
      role: "user",
    },
  ];

  for (const user of users) {
    //암호화
    const hashedPw = await bcrypt.hash(user.password, 10);
    await User.findOrCreate({
      where: { email: user.email }, // 중복 체크는 email로 충분
      defaults: {
        name: user.name,
        password: hashedPw,
        role: user.role,
      },
    });
  }

  console.log("유저 시드 완료");
};

const seedLedgerAndTransactions = async () => {
  try {
    // 1. 유저 찾기 (email 기준)
    const user = await User.findOne({ where: { email: "email@example.com" } });
    if (!user) {
      console.error("user not found");
      return;
    }

    // 2. 가계부 생성 (기존 존재하면 그대로 사용)
    const [ledger] = await Ledger.findOrCreate({
      where: {
        name: "user의 가계부",
        userId: user.id,
      },
      defaults: {
        is_shared: false,
      },
    });

    // 3. 트랜잭션 시드 데이터
    const transactions = [
      // === 6월 지출 (20건) ===
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 12000,
        memo: "점심 식사",
        date: "2025-06-01",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 13000,
        memo: "점심 식사",
        date: "2025-06-07",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 8000,
        memo: "점심 식사",
        date: "2025-06-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 9000,
        memo: "점심 식사",
        date: "2025-06-27",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 2500,
        memo: "버스비",
        date: "2025-06-02",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 5000,
        memo: "아메리카노",
        date: "2025-06-03",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 15000,
        memo: "치과 치료",
        date: "2025-06-04",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 7,
        amount: 32000,
        memo: "의류 구매",
        date: "2025-06-05",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 3500,
        memo: "간식",
        date: "2025-06-07",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 2,
        amount: 22000,
        memo: "보드게임 구매",
        date: "2025-06-08",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 18000,
        memo: "영화 관람",
        date: "2025-06-09",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 6,
        amount: 45000,
        memo: "강의 수강료",
        date: "2025-06-10",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 9000,
        memo: "저녁 식사",
        date: "2025-06-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 3000,
        memo: "택시비",
        date: "2025-06-12",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 4800,
        memo: "카페 라떼",
        date: "2025-06-13",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 20000,
        memo: "내과 진료",
        date: "2025-06-14",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 7,
        amount: 150000,
        memo: "전자제품",
        date: "2025-06-15",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 8,
        amount: 55000,
        memo: "전기요금",
        date: "2025-06-16",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 2500,
        memo: "생수",
        date: "2025-06-17",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 2,
        amount: 12000,
        memo: "서적 구매",
        date: "2025-06-18",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 22000,
        memo: "공연 티켓",
        date: "2025-06-19",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 6,
        amount: 38000,
        memo: "온라인 강의",
        date: "2025-06-20",
      },

      // === 7월 지출 (20건) ===
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 11000,
        memo: "김밥천국",
        date: "2025-07-01",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 23000,
        memo: "야식",
        date: "2025-07-26",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 2400,
        memo: "지하철",
        date: "2025-07-02",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 5200,
        memo: "아이스 라떼",
        date: "2025-07-03",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 17000,
        memo: "정형외과",
        date: "2025-07-04",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 7,
        amount: 28000,
        memo: "모자 구매",
        date: "2025-07-05",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 8,
        amount: 64000,
        memo: "가스 요금",
        date: "2025-07-06",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 4100,
        memo: "아이스크림",
        date: "2025-07-07",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 2200,
        memo: "아이스크림",
        date: "2025-07-23",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 15000,
        memo: "볼링",
        date: "2025-07-09",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 6,
        amount: 50000,
        memo: "영어 회화",
        date: "2025-07-10",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 13000,
        memo: "짜장면",
        date: "2025-07-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 2800,
        memo: "버스",
        date: "2025-07-12",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 4700,
        memo: "콜드브루",
        date: "2025-07-13",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 22000,
        memo: "피부과",
        date: "2025-07-14",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 7,
        amount: 170000,
        memo: "노트북",
        date: "2025-07-15",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 8,
        amount: 58000,
        memo: "수도 요금",
        date: "2025-07-16",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 2900,
        memo: "커피 우유",
        date: "2025-07-17",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 2900,
        memo: "아메리카노",
        date: "2025-07-05",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 2900,
        memo: "아메리카노",
        date: "2025-07-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 2900,
        memo: "아메리카노",
        date: "2025-07-27",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 2,
        amount: 18000,
        memo: "드로잉 도구",
        date: "2025-07-18",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 25000,
        memo: "뮤지컬 관람",
        date: "2025-07-19",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 6,
        amount: 40000,
        memo: "자격증 강의",
        date: "2025-07-20",
      },

      // === 8월 지출 (8/20 이전) ===
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 14000,
        memo: "비빔밥",
        date: "2025-08-01",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 2700,
        memo: "버스비",
        date: "2025-08-02",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 5100,
        memo: "아이스 아메리카노",
        date: "2025-08-03",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 18000,
        memo: "한의원",
        date: "2025-08-04",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 7,
        amount: 33000,
        memo: "여름 옷",
        date: "2025-08-05",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 8,
        amount: 62000,
        memo: "관리비",
        date: "2025-08-06",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 3200,
        memo: "초콜릿",
        date: "2025-08-07",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 2,
        amount: 26000,
        memo: "퍼즐",
        date: "2025-08-08",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 19000,
        memo: "수영장",
        date: "2025-08-09",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 6,
        amount: 52000,
        memo: "프로그래밍 강의",
        date: "2025-08-10",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 15000,
        memo: "돼지국밥",
        date: "2025-08-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 2600,
        memo: "지하철",
        date: "2025-08-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 4800,
        memo: "카페 모카",
        date: "2025-08-12",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 20000,
        memo: "내과 진료",
        date: "2025-08-11",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 4500,
        memo: "편의점 간식",
        date: "2025-08-12",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 12000,
        memo: "라멘",
        date: "2025-08-12",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 5700,
        memo: "콜드브루",
        date: "2025-08-13",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 8,
        amount: 30000,
        memo: "전기요금",
        date: "2025-08-14",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 2700,
        memo: "버스비",
        date: "2025-08-14",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 25000,
        memo: "영화관",
        date: "2025-08-15",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 13000,
        memo: "돈까스",
        date: "2025-08-16",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 15000,
        memo: "약국",
        date: "2025-08-17",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 6200,
        memo: "바닐라 라떼",
        date: "2025-08-17",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 10,
        amount: 9800,
        memo: "택시비",
        date: "2025-08-18",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 2,
        amount: 5500,
        memo: "스팀 게임 구매",
        date: "2025-08-18",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 9,
        amount: 2000,
        memo: "음료",
        date: "2025-08-19",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 5,
        amount: 2000,
        memo: "아메리카노",
        date: "2025-08-20",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 1,
        amount: 14500,
        memo: "샐러드 도시락",
        date: "2025-08-21",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 3,
        amount: 22000,
        memo: "테니스장 이용료",
        date: "2025-08-23",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 4,
        amount: 12000,
        memo: "치과 진료",
        date: "2025-08-24",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 7,
        amount: 47000,
        memo: "여름 샌들",
        date: "2025-08-25",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "expense",
        categoryId: 8,
        amount: 65000,
        memo: "인터넷 요금",
        date: "2025-08-26",
      },

      // === 수입 ===
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "income",
        categoryId: 12,
        amount: 3000000,
        memo: "6월 월급",
        date: "2025-06-01",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "income",
        categoryId: 12,
        amount: 3000000,
        memo: "7월 월급",
        date: "2025-07-01",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "income",
        categoryId: 12,
        amount: 3000000,
        memo: "8월 월급",
        date: "2025-08-01",
      },
      {
        ledgerId: ledger.id,
        userId: user.id,
        type: "income",
        categoryId: 14,
        amount: 200000,
        memo: "중고물품 판매",
        date: "2025-07-15",
      },
    ];

    // await Transaction.bulkCreate(transactions);
    for (const tx of transactions) {
      await Transaction.findOrCreate({
        where: {
          ledgerId: tx.ledgerId,
          userId: tx.userId,
          type: tx.type,
          categoryId: tx.categoryId,
          amount: tx.amount,
          memo: tx.memo,
          date: tx.date,
        },
        default: tx,
      });
    }

    console.log("✅ user의 가계부 + 트랜잭션 시드 완료");
  } catch (error) {
    console.error("❌ 시드 함수 실행 중 에러 발생:", error);
  }
};

const seedSupport = async () => {
  try {
    const supports = [
      {
        title: "서비스 점검 안내 (8월 5일)",
        content:
          "8월 5일 오전 2시부터 4시까지 서비스 점검이 예정되어 있습니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "신규 기능 출시 안내",
        content: "새로운 소비 분석 기능이 추가되었습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "자주 묻는 질문 모음",
        content: "고객님들이 자주 묻는 질문을 모았습니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "8월 휴무 안내",
        content: "8월 15일 광복절은 고객센터가 운영되지 않습니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "버그 수정 공지",
        content: "가계부 통계 오류가 수정되었습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "회원 등급별 혜택 안내",
        content: "프리미엄 회원에게 제공되는 혜택을 안내합니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "서비스 이용약관 개정 안내",
        content: "2025년 8월 1일부터 약관이 변경됩니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "데이터 백업 안내",
        content: "월말 정기 백업 작업이 진행됩니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "공유 가계부 사용법",
        content: "공유 가계부를 시작하는 방법을 알아보세요.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "고객센터 운영시간 변경 안내",
        content: "운영시간이 오전 9시부터 오후 6시로 변경됩니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "알림 기능 개선 안내",
        content: "불필요한 알림을 줄이고, 맞춤형 알림을 제공합니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "앱 버전 업데이트 안내",
        content: "최신 앱 버전을 마켓에서 다운로드하세요.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "소비 트렌드 분석 가이드",
        content: "지난달 소비 트렌드를 확인하는 방법을 소개합니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "이벤트 종료 안내",
        content: "7월 여름 이벤트가 종료되었습니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "앱 속도 개선 공지",
        content: "로딩 속도가 최대 2배 빨라졌습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "FAQ 업데이트",
        content: "최근 자주 묻는 질문을 반영해 FAQ를 수정했습니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "정기 점검 예고 (9월)",
        content: "9월 1일 자정부터 정기 점검이 예정되어 있습니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "앱 알림 설정 방법",
        content: "알림을 끄거나 키는 방법을 확인하세요.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "데이터 복구 지원 안내",
        content: "실수로 삭제한 데이터를 복구하는 방법을 안내합니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "서비스 안정화 작업 안내",
        content: "더 나은 서비스를 위한 내부 점검이 있습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "소비 카테고리 추가 안내",
        content: "새로운 소비 카테고리를 선택할 수 있게 되었습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "가계부 백업 기능 안내",
        content: "가계부 내보내기 기능을 사용할 수 있습니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "추석 연휴 운영 안내",
        content: "추석 기간 동안 고객센터 운영시간이 변경됩니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "계정 보안 강화 안내",
        content: "2단계 인증 기능이 추가되었습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "데이터 삭제 유의사항",
        content: "데이터 삭제 시 복구가 어렵습니다. 주의해주세요.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "이메일 수신 설정 변경 안내",
        content: "원하지 않는 메일은 수신거부가 가능합니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "공지사항 탭 위치 변경 안내",
        content: "메뉴 내 공지사항 위치가 변경되었습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "회원 탈퇴 전 확인사항",
        content: "탈퇴 전 확인해야 할 내용을 안내합니다.",
        post_type: "가이드",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "이벤트 당첨자 발표",
        content: "이벤트에 참여해주셔서 감사합니다.",
        post_type: "공지",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "업데이트 내역 정리",
        content: "8월 업데이트 주요 내용을 정리했습니다.",
        post_type: "업데이트",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    for (const post of supports) {
      await SupportPost.findOrCreate({
        where: {
          title: post.title,
          content: post.content,
          post_type: post.post_type,
          createdAt: post.createdAt,
          updatedAt: post.updatedAt,
        },
      });
    }
    console.log("공지사항 시드 완료");
  } catch (error) {
    console.error("❌ 시드 함수 실행 중 에러 발생:", error);
  }
};

module.exports = {
  seedCategories,
  seedUsers,
  seedLedgerAndTransactions,
  seedSupport,
};
